# Generated by Django 3.2.3 on 2021-07-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('latitude', models.IntegerField(blank=True)),
                ('longitude', models.IntegerField(blank=True)),
            ],
        ),
    ]
