# Generated by Django 3.2.3 on 2021-07-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.IntegerField(null=True),
        ),
    ]
