# Generated by Django 3.2.4 on 2021-07-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='icon',
            field=models.CharField(choices=[('N', 'Neutral'), ('L', 'Like'), ('D', 'Dislike')], default='N', max_length=1, verbose_name='reaction'),
        ),
    ]
